#!/bin/sh -e


psql -q -v ON_ERROR_STOP=1 wbpgg << EOF
DELETE FROM users_stops
  WHERE weatherbus_user_id IN (SELECT id FROM weatherbus_user WHERE username = 'contractuser');
DELETE FROM weatherbus_user WHERE username = 'contractuser';
