#!/usr/bin/env ruby
require 'net/http'

def started
  begin
    Net::HTTP.get(URI('http://localhost:8080/healthcheck')) == 'ok'
  rescue Errno::ECONNREFUSED
    false
  end
end

orig_dir = Dir.pwd
Dir.chdir('../weatherbus')
puts 'Building weatherbus'
if !system('./gradlew', 'build', {:out => '/dev/null'})
  exit(1)
end

if started
  puts 'There is already a running weatherbus.'
  exit(1)
end

puts 'Starting weatherbus'
# TODO: pass --spring.profiles.active=goldengardens  after the jar once we have isolation working
pid = spawn('java', '-jar', 'build/libs/weatherbus-SNAPSHOT.jar', {:out => '/dev/null'})

begin
  puts 'Waiting for weatherbus to start'
  
  while !started
    sleep 1
  end

  Dir.chdir(orig_dir) 
  if !system('perspectives/prime/verify-contracts')
    exit(1)
  end
ensure
  puts 'Stopping weatherbus'
  Process.kill('TERM', pid)
  Process.waitpid(pid)
end
