#!/bin/sh -e

die() {
  echo "$1"
  exit 1
}

create_database() {
  if ! output=`createdb wbpgg 2>&1`; then
    if !  echo "$output" | fgrep 'database "wbpgg" already exists' > /dev/null; then
      die "Failed to create database: $output"
    fi
  fi
}

create_database
java -jar ../weatherbus/build/libs/weatherbus-SNAPSHOT.jar --spring.profiles.active=goldengardens
